world:
  # medium-pace model
  a1: 15.77
  a2: 40.97
  a3: 0.21
  a4: 19.82
  a5: 2.93
  a6: 0.4
  # UN medium-pace model, however, I wasn't able to find the values
  delta_1_sq: 1.0
  delta_2_sq: 1.0
  delta_3_sq: 1.0
  delta_4_sq: 1.0
  delta_5_sq: 1.0
  delta_6_sq: 1.0
  rate_1: 15.6
  rate_2: 23.5
  rate_3: 14.5
  rate_4: 14.7
  rate_5: 3.5
  rate_6: 0.6
  # Initial distribution (Right skewed Gambel distribution)
  gambel_loc: 43.879419661749694
  gambel_scale: 10.832300773004311
